-- MySQL Script generated by MySQL Workbench
-- Mon Dec 25 19:46:36 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema sghvet
-- -----------------------------------------------------


drop schema if exists sghvet;
create schema if not exists sghvet;
use sghvet;

CREATE USER IF NOT EXISTS '10103566406'@'localhost' IDENTIFIED BY '301716283811389038011477436469853762335';
-- senha de admsupremo eh 'abcd'


FLUSH PRIVILEGES;
GRANT CREATE USER, RELOAD ON *.* TO '10103566406'@'localhost' WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON sghvet.* TO '10103566406'@'localhost';
FLUSH PRIVILEGES;
SET FOREIGN_KEY_CHECKS = 0;


-- -----------------------------------------------------
-- Table `sghvet`.`usuario`
-- -----------------------------------------------------


CREATE TABLE usuario(
cpf char(11) not null,
tipo enum('VETERINARIO', 'ADMINISTRATIVO', 'AUXILIAR' ,'ALUNO') not null,
primary key(cpf)
)ENGINE = innodb;


-- -----------------------------------------------------
-- Table `sghvet`.`veterinario`
-- -----------------------------------------------------

CREATE TABLE veterinario(

nome varchar(100) not null,
cpf char(11) not null,
dataNasc date not null,
cargo enum('CLINICO', 'CIRURGIAO') not null,
contato varchar(12) not null,
email varchar(40) not null,
crmv varchar(20) not null, 
primary key(cpf),
foreign key (cpf)references usuario(cpf)
ON DELETE CASCADE
)ENGINE = innodb;

-- -----------------------------------------------------
-- Table `sghvet`.`administrativo`
-- -----------------------------------------------------

CREATE TABLE administrativo(

nome varchar(100) not null,
cpf char(11) not null,
dataNasc date not null,
cargo enum('ATENDENTE',  'ADMINISTRADOR') not null,
contato varchar(12) not null,
email varchar(40) not null,
primary key(cpf),
foreign key (cpf) references usuario(cpf)
ON DELETE CASCADE
)ENGINE = innodb;

-- -----------------------------------------------------
-- Table `sghvet`.`auxiliar`
-- -----------------------------------------------------

CREATE TABLE auxiliar(

nome varchar(100) not null,
cpf char(11) not null,
dataNasc date not null,
cargo enum('LABORATORIO', 'FARMACEUTICO') not null,
crf VARCHAR(45),
contato varchar(12) not null,
email varchar(40) not null,
primary key(cpf),
foreign key (cpf) references usuario(cpf)
ON DELETE CASCADE
)ENGINE = innodb;

-- -----------------------------------------------------
-- Table `bdsghvet`.`aluno`
-- -----------------------------------------------------
CREATE TABLE aluno(
  id_aluno int  auto_increment,
  matricula INT NOT NULL,
  cpf char(11) not null,
  nome VARCHAR(45) NOT NULL,
  curso VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  periodo VARCHAR(45) NOT NULL,
  turma VARCHAR(45) NOT NULL,
  contato VARCHAR(12) NOT NULL,
  PRIMARY KEY (id_aluno),
  foreign key (cpf)references usuario(cpf)
  ON DELETE CASCADE
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `sghvet`.`cargoAdm`
-- -----------------------------------------------------
CREATE TABLE cargoAdm(
cpf char(11) not null,
tipo enum('ATENDENTE',  'ADMINISTRADOR') not null,
primary key(cpf),
foreign key (cpf)references administrativo(cpf)
)ENGINE = innodb;

-- -----------------------------------------------------
-- Table `sghvet`.`cargoAuxiliar`
-- -----------------------------------------------------
CREATE TABLE cargoAuxiliar(
cpf char(11) not null,
tipo enum('LABORATORIO', 'FARMACEUTICO') not null,
primary key(cpf),
foreign key (cpf)references auxiliar(cpf)
)ENGINE = innodb;


-- -----------------------------------------------------
-- Table `sghvet`.`cargosVeterinario`
-- -----------------------------------------------------
CREATE TABLE cargosVeterinario(
cpf char(11) not null,
tipo enum('CLINICO', 'CIRURGIAO') not null,

primary key(cpf),
foreign key (cpf)references veterinario(cpf)
)ENGINE = innodb;
-- -----------------------------------------------------
-- Table `sghvet`.`tutor`
-- -----------------------------------------------------


CREATE TABLE tutor(
nome varchar(100) not null,
cpf char(11) not null,
sexo char(1) not null,
contato varchar(11) not null,
primary key(cpf)
)ENGINE = innodb;

-- -----------------------------------------------------
-- Table `sghvet`.`endereco`
-- -----------------------------------------------------

CREATE TABLE endereco(
id int  auto_increment,
rua varchar(100) not null,
bairro varchar(100) not null,
numero varchar(5),
complemento varchar(100),
cep char(8) not null,
cidade varchar(30) not null,
estado varchar(30) not null,
cpfTutor char(11) not null,
primary key(id),
foreign key(cpfTutor) references tutor(cpf)
ON DELETE CASCADE
)ENGINE = innodb;


-- -----------------------------------------------------
-- Table `sghvet`.`especie`
-- -----------------------------------------------------
CREATE TABLE especie(
  codEsp INT auto_increment,
  nome VARCHAR(45) NOT NULL,
  PRIMARY KEY (codEsp)
)ENGINE = innodb;


-- -----------------------------------------------------
-- Table `sghvet`.`raça`
-- -----------------------------------------------------
CREATE TABLE raça (
  codRac INT auto_increment,
  nome VARCHAR(45) NOT NULL,
  cod_esp INT NOT NULL,
  PRIMARY KEY (codRac),
  FOREIGN KEY (cod_esp) REFERENCES especie(codEsp) 
  ON DELETE CASCADE
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `sghvet`.`animal`
-- -----------------------------------------------------

CREATE TABLE animal(
prontuario int auto_increment,	
nome varchar(50) not null,
especie varchar(50) not null,
raca varchar(50),
pelagem varchar(50),
peso decimal(5,2),
sexo char(1)not null,
idade int not null,
cpfTutor char(11) not null,

primary key(prontuario,cpfTutor),
foreign key(cpfTutor) references tutor(cpf)
ON DELETE CASCADE
)ENGINE = innodb;



-- -----------------------------------------------------
-- Table `sghvet`.`consulta`
-- -----------------------------------------------------

CREATE TABLE consulta(
id int AUTO_INCREMENT,
dia date not null,
horario time not null,
cpf_tutor char(11) not null,
concluido boolean default false,
prontuario int not null,
cpf_vet char(11) not null,
primary key(id),
foreign key(cpf_tutor) references tutor(cpf),
foreign key(cpf_vet) references veterinario(cpf),
foreign key(prontuario) references animal(prontuario)
ON DELETE CASCADE
) ENGINE = innodb;


-- -----------------------------------------------------
-- Table `sghvet`.`disponibilidade_vet`
-- -----------------------------------------------------

CREATE TABLE disponibilidade_vet(
    cpf_vet char(11) not null, 
    horario_inicio time not null,
    horario_fim  time not null,
    dia enum('segunda','terca','quarta','quinta','sexta','sabado','domingo'),
    primary key(cpf_vet,dia),
    foreign key(cpf_vet) references veterinario(cpf)
) ENGINE = innodb;

-- -----------------------------------------------------
-- Table `sghvet`.`exame`
-- -----------------------------------------------------

CREATE TABLE exame(
    id int AUTO_INCREMENT,
    cpf_aux char(11) not null,
    cpf_tutor char(11) not null,
    prontuario int not null,
    data_exame date not null,
    realizado boolean default '0',
    foreign key(cpf_aux) references auxiliar(cpf),
    foreign key(cpf_tutor) references tutor(cpf), 
    foreign key(prontuario) references animal(prontuario),
    primary key(id)
) ENGINE = innodb;

-- -----------------------------------------------------
-- Table `sghvet`.`registro`
-- -----------------------------------------------------

CREATE TABLE registro(
	id_exame int AUTO_INCREMENT,
    temperatura float,
    batimentoPorMin float,
    movRespPorMin float,
    pulso float,
    ectoscopia varchar(300),
    vacinacoes varchar(300),
    vermifugacoes varchar(300),
    cabecaPescoco varchar(300),
    cavidadeToracica varchar(300),
    cavidadeAbdominal varchar(300),
    sistemaLocomotor varchar(300),
    sistemaNervoso varchar(300),
    diagnosticoProvavel varchar(150),
    examesComplementares varchar(150),
    diagnosticoDefinitivo varchar(150),
    prognostico varchar(150),
    primary key (id_exame),
    foreign key (id_exame) references consulta(id) 
) ENGINE = innodb;

-- -----------------------------------------------------
-- Table `sghvet`.`logDataHoraVet`
-- -----------------------------------------------------

CREATE TABLE logDataHoraVet(
  codlog int  auto_increment,
  nome VARCHAR(45) NOT NULL,
  data_cadastro DATETIME not null,
  id_vet int not null,
  PRIMARY KEY (codlog)
 )ENGINE = innodb;
 
 -- -----------------------------------------------------
-- Table `sghvet`.`logDataHoraVet`
-- -----------------------------------------------------

CREATE TABLE logDataHoraAux(
  codlog int  auto_increment,
  nome VARCHAR(45) NOT NULL,
  data_cadastro DATETIME not null,
  id_aux int not null,
  PRIMARY KEY (codlog)
 )ENGINE = innodb;
 
 -- -----------------------------------------------------
-- Table `sghvet`.`logDataHoraVet`
-- -----------------------------------------------------

CREATE TABLE logDataHoraAdm(
  codlog int  auto_increment,
  nome VARCHAR(45) NOT NULL,
  data_cadastro DATETIME not null,
  id_adm int not null,
  PRIMARY KEY (codlog)
 )ENGINE = innodb;

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

--------------------------------------------------
-- Table `sghvet`.`cirurgia`
-- -----------------------------------------------------
CREATE TABLE cirurgia (
  id INT(11) AUTO_INCREMENT,
  tipo enum('GERAL', 'ESPECISLISTA') not null,
  especialidade varchar(60), 
  data_cir date NOT NULL,
  hr_fim time,
  sala enum('SALA_A', 'SALA_B', 'SALA_C', 'SALA_D' , 'SALA_E') NOT NULL,
  hr_inic time NOT NULL,
  prontuario INT(11) NOT NULL,
  PRIMARY KEY (id),
    FOREIGN KEY (prontuario) REFERENCES animal (prontuario)  
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sghvet`.`equipe_cirurgica`
-- -----------------------------------------------------
CREATE TABLE membro_cirurgia (
  id INT(11) AUTO_INCREMENT,
  id_cirur INT(11) NOT NULL,
  cpf_membro char(11) NOT NULL,
  PRIMARY KEY (id),
	FOREIGN KEY(id_cirur) REFERENCES cirurgia(id),
    FOREIGN KEY(cpf_membro) REFERENCES veterinario(cpf) 
)ENGINE = InnoDB;


-- ------------------------------------------------------- -----------------------------------------------------
-- FARMACIA
-- ------------------------------------------------------- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `bdsghvet`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS estoque (
id INT(11) NOT NULL,
tipo VARCHAR(45) NOT NULL,
descricao  VARCHAR(45) NOT NULL,
nome VARCHAR(45) NOT NULL,
PRIMARY KEY (id)

)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsghvet`.`farmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS farmacia(
codigo INT(11) NOT NULL,
nome VARCHAR(45) NOT NULL,
descricao VARCHAR(45) NOT NULL,
id_estoque_f INT(11) NOT NULL,
PRIMARY KEY (codigo),
FOREIGN KEY (id_estoque_f) REFERENCES estoque (`id`)

)ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `bdsghvet`.`tratamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS tratamento(
id_tratamento INT(11) NOT NULL,
id_diagnostico INT(11) NOT NULL,
status VARCHAR(45) NOT NULL,
descricao VARCHAR(45) NOT NULL,
dt_inicio date NOT NULL,
dt_fim date NOT NULL,
PRIMARY KEY (id_tratamento),
FOREIGN KEY (id_diagnostico)  REFERENCES registro (id_exame)

)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `bdsghvet`.`receituario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS receituario(
seq INT(11) NOT NULL,
dt_emissão date NOT NULL,
id_tratamento_r INT(11) NOT NULL,
PRIMARY KEY (seq),
FOREIGN KEY (id_tratamento_r) REFERENCES tratamento (id_tratamento)

)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `bdsghvet`.`remedio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS remedio(
codigo INT(11) NOT NULL,
nome VARCHAR(45) NOT NULL,
bula VARCHAR(45) NOT NULL,
substacia_principal VARCHAR(45) NOT NULL,
restrição VARCHAR(45) NOT NULL,
unidade VARCHAR(45) NOT NULL,
seq_receita_r INT(11) NOT NULL,
PRIMARY KEY (codigo),
FOREIGN KEY (seq_receita_r) REFERENCES receituario (seq)
)ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `bdsghvet`.`intem_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS intem_estoque(
data_entrada date NOT NULL,
qtd_min VARCHAR(45) NOT NULL,
sequencial VARCHAR(45) NOT NULL,
preço_compra VARCHAR(45) NOT NULL,
data_final date NOT NULL,
data_validade date NOT NULL,
qtd_atual INT NOT NULL,
id_estoque_ie INT(11) NOT NULL,
codigo_remedio_ie INT(11) NOT NULL,
PRIMARY KEY (id_estoque_ie, sequencial, codigo_remedio_ie),
FOREIGN KEY (codigo_remedio_ie) REFERENCES remedio(codigo),
FOREIGN KEY (id_estoque_ie) REFERENCES estoque(id)

)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `bdsghvet`.`terceirizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS terceirizado(
id_terc INT NOT NULL,
nome varchar(70),
cpf char(11),
PRIMARY KEY (id_terc)
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `bdsghvet`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS servico(
id_servico INT NOT NULL,
descricao char(100),
id_executor int,
PRIMARY KEY (id_servico),
FOREIGN KEY (id_executor) REFERENCES terceirizado(id_terc) ON DELETE CASCADE
)ENGINE = InnoDB;

-- -----------------------------------------------------
INSERT INTO sghvet.usuario (`cpf`, `tipo`) VALUES ('10103566406', 'ADMINISTRATIVO');
INSERT INTO sghvet.administrativo (nome, cpf, dataNasc, cargo, contato, email) VALUES ('admS', '10103566406', '1990-12-30', 'ADMINISTRADOR', '99998888', 'adm@adm.com');